In [1]:
%load_ext autoreload
%autoreload 2

import tensorflow as tf
from src.custom.metrics import Levenshtein

In [2]:
a = tf.constant([[1, 2, 3, 4, 0, 0 ,0]])
b = tf.constant([[1, 2, 3, 4, 0, 0 ,0]])
d = tf.constant([[1, 2, 5, 4, 0, 0 ,0]])

In [3]:
a_lenght = a.shape[1]
b_lenght = b.shape[1]

tf.math.reduce_sum(tf.cast(tf.not_equal(a, b), dtype="int32"))

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [4]:
a_sparse = tf.sparse.from_dense(a)
b_sparse = tf.sparse.from_dense(b)
d_sparse = tf.sparse.from_dense(d)

tf.edit_distance(a_sparse, b_sparse)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [5]:
tf.edit_distance(a_sparse, d_sparse)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.25], dtype=float32)>

In [30]:
lev_dist = Levenshtein()

In [29]:
lev_dist(a, b)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9285714>

In [31]:
lev_dist(b, d)

<tf.Tensor: shape=(), dtype=float32, numpy=0.75>

In [32]:
lev_dist(b, d)

<tf.Tensor: shape=(), dtype=float32, numpy=0.75>

In [33]:
lev_dist.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.75>