In [1]:
%load_ext autoreload
%autoreload 2

import tensorflow as tf
from src.custom.metrics import Levenshtein

2023-08-18 22:06:49.973961: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-18 22:06:50.639372: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
a = tf.constant([[1, 2, 3, 4, 0, 0 ,0]])
b = tf.constant([[1, 2, 3, 4, 0, 0 ,0]])
d = tf.constant([[1, 2, 5, 4, 0, 0 ,0]])

2023-08-18 22:06:51.422636: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-18 22:06:51.441666: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-18 22:06:51.441808: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [3]:
a_lenght = a.shape[1]
b_lenght = b.shape[1]

tf.math.reduce_sum(tf.cast(tf.not_equal(a, b), dtype="int32"))

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [4]:
a_sparse = tf.sparse.from_dense(a)
b_sparse = tf.sparse.from_dense(b)
d_sparse = tf.sparse.from_dense(d)

tf.edit_distance(a_sparse, b_sparse)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [5]:
tf.edit_distance(a_sparse, d_sparse)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.25], dtype=float32)>

In [6]:
tf.cast(tf.argmax([[0.1, 0.3, 0.6], [0.2, 0.2, 0.6]]), dtype=tf.int32)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 0], dtype=int32)>

In [7]:
import numpy as np 


np.array([[0.9, 0.1, 0.0, 0.0, 0.0],
           [0.0, 0.9, 0.1, 0.0, 0.0],
           [0.0, 0.0, 1.0, 0.0, 0.0],
           [0.0, 0.0, 0.0, 1.0, 0.0],
           [1.0, 0.0, 0.0, 0.0, 0.0],
           [1.0, 0.0, 0.0, 0.0, 0.0],
           [1.0, 0.0, 0.0, 0.0, 0.0]])

array([[0.9, 0.1, 0. , 0. , 0. ],
       [0. , 0.9, 0.1, 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 1. , 0. ],
       [1. , 0. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 0. , 0. ]])

In [8]:
a_true = tf.constant([[1, 2, 3, 4, 0, 0 ,0]])
b_true = tf.constant([[1, 2, 3, 4, 0, 0 ,0]])
d_true = tf.constant([[1, 2, 5, 4, 0, 0 ,0]])

a_pred = tf.constant([[[0.9, 0.1, 0.0, 0.0, 0.0],
           [0.0, 0.9, 0.1, 0.0, 0.0],
           [0.0, 0.0, 1.0, 0.0, 0.0],
           [0.0, 0.0, 0.0, 1.0, 0.0],
           [1.0, 0.0, 0.0, 0.0, 0.0],
           [1.0, 0.0, 0.0, 0.0, 0.0],
           [1.0, 0.0, 0.0, 0.0, 0.0]]])

lev_dist = Levenshtein()

In [9]:
tf.shape(a_true)[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [10]:
a_true.shape

TensorShape([1, 7])

In [11]:
a_pred.shape

TensorShape([1, 7, 5])

In [12]:
tf.argmax(a_pred, axis=2)

<tf.Tensor: shape=(1, 7), dtype=int64, numpy=array([[0, 1, 2, 3, 0, 0, 0]])>

In [13]:
lev_dist(a_true, a_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.6666666>

In [ ]:
#test
model = build_transformer_model(trial=None)
prediction = model.predict(({"source": tf.random.uniform(shape=(1, 120, 84)), "target":tf.random.uniform(shape=(1, 32))}))
model.evaluate({"source": tf.random.uniform(shape=(1, 120, 84)), "target":tf.random.uniform(shape=(1, 32))}, tf.cast(tf.argmax(prediction, axis=2), dtype=tf.int32))