In [ ]:
%load_ext autoreload
%autoreload 2

import tensorflow as tf

from src.custom.layers import LandmarkEmbeddingV2, LandmarkEmbedding

In [ ]:
# input 1, 120, 84
# output 1, 120, 64(embedding size)

with tf.device("CPU") as d:
    example = tf.concat([tf.random.uniform(shape=(1, 120, 10)), tf.zeros(shape=(1, 120, 10))], axis=2)
    embedding_v1 = LandmarkEmbedding(max_seq_length=example.shape[1], embedings_dim=16)(example)
    embedding_v1_global = tf.keras.layers.MaxPooling1D() (embedding_v1)

In [47]:
embedding_v1.numpy()[:, 3, :8]

array([[-0.01085198,  0.03209967,  0.03633299,  0.11093532, -0.00099474,
         0.02518087,  0.03662939, -0.02049491]], dtype=float32)

In [48]:
embedding_v1.numpy()[:, 3, 8:]

array([[-0.03285915,  0.0029701 ,  0.01096784,  0.07470722,  0.12983623,
         0.07551292,  0.03705879,  0.02305299]], dtype=float32)

In [50]:
# input 1, 120, 84
# output 1, 120, 64(embedding size)

with tf.device("CPU") as d:
    example = tf.concat([tf.random.uniform(shape=(1, 120, 10)), tf.zeros(shape=(1, 120, 10))], axis=2)
    embedding_v2 = LandmarkEmbeddingV2(max_seq_length=example.shape[1], embedings_dim=16)(example)
    embedding_v2_global = tf.keras.layers.MaxPooling1D() (embedding_v1)

In [54]:
embedding_v2

<tf.Tensor: shape=(1, 8, 16), dtype=float32, numpy=
array([[[0.09464418, 0.        , 0.        , 0.00812051, 0.        ,
         0.        , 0.10896625, 0.04925282, 0.25329977, 0.        ,
         0.        , 0.        , 0.08235689, 0.09233984, 0.08808932,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.1843084 , 0.03365577, 0.25340894, 0.        ,
         0.        , 0.05378824, 0.1607976 , 0.1761772 , 0.10532144,
         0.        ],
        [0.04267894, 0.00639175, 0.05484967, 0.        , 0.1212037 ,
         0.        , 0.30545348, 0.14641222, 0.13824981, 0.        ,
         0.        , 0.2945755 , 0.10249932, 0.01398341, 0.15127106,
         0.        ],
        [0.10497778, 0.08764037, 0.01495724, 0.        , 0.05379348,
         0.03941846, 0.37582898, 0.02180339, 0.19262014, 0.        ,
         0.        , 0.13429514, 0.11878841, 0.        , 0.14607774,
         0.        ],
        [0.        , 0.00937076,

In [51]:
embedding_v2.numpy()[:, 3, :8]

array([[0.10497778, 0.08764037, 0.01495724, 0.        , 0.05379348,
        0.03941846, 0.37582898, 0.02180339]], dtype=float32)

In [52]:
embedding_v1.numpy()[:, 3, 8:]

array([[0.        , 0.        , 0.        , 0.2830974 , 0.        ,
        0.06640601, 0.16579297, 0.07952956]], dtype=float32)

In [53]:
embedding_v2_global

<tf.Tensor: shape=(1, 4, 16), dtype=float32, numpy=
array([[[0.        , 0.09814413, 0.05674899, 0.16920596, 0.10009627,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.23619582, 0.        , 0.30828908, 0.08720254,
         0.24923205],
        [0.        , 0.1103146 , 0.09330197, 0.31628802, 0.08891925,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.2830974 , 0.        , 0.06640601, 0.25431204,
         0.07952956],
        [0.        , 0.04474241, 0.02492156, 0.3198914 , 0.16038942,
         0.        , 0.        , 0.        , 0.11757287, 0.        ,
         0.        , 0.3291516 , 0.        , 0.20944715, 0.1500537 ,
         0.2528688 ],
        [0.        , 0.        , 0.08513737, 0.12256526, 0.05610771,
         0.        , 0.        , 0.        , 0.17094883, 0.        ,
         0.        , 0.22840646, 0.00790988, 0.19344397, 0.15497917,
         0.        ]]], dtype=float32)>

In [55]:
tf.constant(-1)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>